### ISSUE TITLE
whatever this is

### ISSUE THREAD

**Issue by nightietime** [kitkatyj/kitkatyj.github.io#1]
![image](https://user-images.githubusercontent.com/9695392/79470753-fb857d00-802b-11ea-9857-6c5bb8b5fbe6.png)

**Comment by kitkatyj** [comment]
<img width="654" alt="Screenshot 2020-04-16 at 11 58 50 PM" src="https://user-images.githubusercontent.com/21078920/79478641-3b556000-803e-11ea-9357-61ca73bf3be9.png">
I was using twinkleOffset instead of zIndex. No wonder my stars were looking a little off.
